


from typing import Any, Dict, List, Optional 
from pydantic import BaseModel , Field
from langchain_core.prompts import ChatPromptTemplate
  

class SingleWorkflowStepFormat(BaseModel) :
     
    step_number : int # step number for order
    
    tool_name : str # name of the tool to call
    
    tool_desc : str # description of the tool to call 
    
    params_required : List[str] # parameters for the tool call
  
  
class ReasoningAgentResponseFormat(BaseModel) : # response format expected from the agent
    
    is_new_workflow : bool # to verify the workflow is new or not
    
    workflow_id : Optional[int] = None # if using a old workflow what's it's id
    
    workflow_name : str # a name for this new workflow 
    
    workflow_description : str # a short desc for this generated workflow
    
    workflow_steps : List[SingleWorkflowStepFormat] # steps to follow
    
    confidence_score : float # self evaluation rating by the agent from 0.0 to 1.0
    
    reasoning : str # reason for choosing this workflow  
  
class InputState(BaseModel) : # state to be passed as input
    
    user_input : str # input prompt 
    
    user_session : str # session from login
    
    is_new_chat : bool # True / False helps to set memory
    
    chat_session : Optional[int] = None # chat session -> not needed if a new chat
    
    user_input_id : int # initially set to -1 will be updated to the proper id on verifying the user
    
class FlagState(BaseModel) : # state which acts as a flag to check the status of execution of previous states
    
    status : str # to mark success / error
    
    message : str # corresponding error message
    
class SingleMessageFormat(BaseModel) : # format of a single message
    
    chat_id : int # same as user input id the id for the msg 
    
    user_message : str # the prompt given by the user
    
    ai_message : ReasoningAgentResponseFormat # the response format expected from the reasoning agent
    
class SingleRelevantWorkflowFormat(BaseModel) : # state to hold the relevant workflows
    
    chat_id : int # same as the user input id
    
    user_message : str # that relevant prompt from user
    
    ai_message : ReasoningAgentResponseFormat # workflow generated by the agent for it
    
class ReasoningAgentInputState(BaseModel) :  # this state holds the user chat history as memory and relevant workflows to pass to the reasoning agent as input
    
    user_input_id : int # this is the config id for unique identification 
    
    user_input : str
    
    chat_session : int # the chat session whose memory is stored
    
    history_messages : List[SingleMessageFormat] # List of Messages from history
    
    summary : str # summary of the previous messages to reduce context window
    
    relevant_workflows : Optional[List[SingleRelevantWorkflowFormat]] = []# List of relevant workflows
    
    prompt : Optional[str] = "" # the final prompt to send to the agent
    
    additional_message : Optional[str] = ""
    
class ReasoningAgentResponseState(BaseModel) : 
    
    raw_response : str
    
    formatted_response : ReasoningAgentResponseFormat
    
